### ISSUE TITLE
Error in ToolTip Component in SideBar 

### ISSUE THREAD

**Issue by shivambalwani** [react-native-elements/playground#81] opened 2021-03-17 08:07 UTC
Issue:
when clicking on hello there 
<img width="1433" alt="Screenshot 2021-03-17 at 1 19 58 PM" src="https://user-images.githubusercontent.com/71224988/111434068-1f15e380-8725-11eb-86b7-f377f1d57a36.png">
<img width="1268" alt="Screenshot 2021-03-17 at 1 20 03 PM" src="https://user-images.githubusercontent.com/71224988/111434109-2806b500-8725-11eb-95af-7ff654f5128b.png">
The pop up shown needs proper alignment and styling .

Possible Solution:
 1.Providing proper alignment to "hello there" area .
2. Applying styling so that "hello there" is clearly visible on the pop up area.

**Comment by abhishekkumar08** [comment] 2021-03-17 08:43
This looks like a duplicate of #34

**Closed** 2021-03-17 13:11 UTC
